[package]
name = "matrix_mul"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
ndarray-linalg = {vertion = "0.16.0", features = ["openblas"]}
rand = "0.6"
